# Generated by Django 5.2.7 on 2026-04-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='ticket_number',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
