# Generated by Django 5.2.7 on 2026-04-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_ticket_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text (Paragraph)'), ('dropdown', 'Dropdown Selection'), ('number', 'Positive Number'), ('image', 'Image Upload'), ('checkbox', 'Checkbox')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('NotResolved', 'Pending'), ('InProgress', 'In Progress'), ('Resolved', 'Resolved')], default='NotResolved', max_length=20),
        ),
    ]
