# Generated by Django 5.2.7 on 2026-04-03 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_alter_categoryfield_field_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryfield',
            name='options',
            field=models.TextField(blank=True, help_text='[Legacy] Comma-separated options for dropdowns', null=True),
        ),
        migrations.CreateModel(
            name='FieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_options', to='complaints.categoryfield')),
            ],
        ),
        migrations.AddField(
            model_name='categoryfield',
            name='parent_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_fields', to='complaints.fieldoption'),
        ),
    ]
