# Generated by Django 5.2.7 on 2026-04-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostelFloorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_number', models.CharField(max_length=50)),
                ('floor_number', models.IntegerField()),
                ('total_rooms', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('hostel_number', 'floor_number')},
            },
        ),
    ]
