# Generated by Django 5.2.7 on 2025-11-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warden', '0002_wardenprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardenprofile',
            name='first_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wardenprofile',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
