# Generated by Django 5.2.7 on 2026-04-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warden', '0003_wardenprofile_first_login_wardenprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardenprofile',
            name='hostel_number',
            field=models.CharField(blank=True, default='Hostel 1', max_length=20),
        ),
    ]
