# Generated by Django 5.2.7 on 2026-04-14 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warden', '0004_wardenprofile_hostel_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wardenprofile',
            name='phone',
        ),
    ]
