# Generated by Django 5.2.7 on 2026-04-14 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warden', '0005_remove_wardenprofile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wardenprofile',
            name='department',
        ),
    ]
