# """
# Django settings for hostel_portal project.

# Generated by 'django-admin startproject' using Django 5.2.7.

# For more information on this file, see
# https://docs.djangoproject.com/en/5.2/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/5.2/ref/settings/
# """

# from pathlib import Path
# from decouple import config

# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent


# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure--k^i@#ri*g!a*yb(iaea!)kgw6_ab^0uq!cule83zj5wjf5!kx'

# # SECURITY WARNING: don't run with debug turned on in production!
# # DEBUG = True

# # ALLOWED_HOSTS = []
# DEBUG = config('DEBUG', default=False, cast=bool)
# ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost').split(',')

# # Application definition

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'accounts',
#     'social_django',
#     'warden',
#     'complaints',
# ]

# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
#     'social_django.middleware.SocialAuthExceptionMiddleware',
#     'accounts.middleware.CustomSocialAuthExceptionMiddleware',
# ]

# ROOT_URLCONF = 'hostel_portal.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [BASE_DIR / 'templates'],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#                 'social_django.context_processors.backends',         # ✅ Add this
#                 'social_django.context_processors.login_redirect',   # ✅ And this
#             ],
#         },
#     },
# ]


# WSGI_APPLICATION = 'hostel_portal.wsgi.application'


# # Database
# # https://docs.djangoproject.com/en/5.2/ref/settings/#databases


# # Create a New Database, in postgres
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'hostel_portal',           # pgAdmin DB name
#         'USER': 'postgres',            # pgAdmin username
#         'PASSWORD': '1234',            # pgAdmin password
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }


# # Password validation
# # https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/5.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

# USE_I18N = True

# USE_TZ = True


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = '/static/'
# STATICFILES_DIRS = [ BASE_DIR / 'static' ]

# # Default primary key field type
# # https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# #============ADDED===============

# AUTHENTICATION_BACKENDS = (
#     'social_core.backends.google.GoogleOAuth2',
#     'django.contrib.auth.backends.ModelBackend',
# )

# LOGIN_URL = 'google_login_redirect'         # 👈 This should match your redirect view name
# # LOGIN_REDIRECT_URL = 'profile_edit'      # 👈 After login, go to profile edit
# LOGIN_REDIRECT_URL =   '/accounts/login-redirect/'  # ✅ Safe fallback, pipeline will override
# # LOGOUT_REDIRECT_URL = 'google_login_redirect'
# LOGOUT_REDIRECT_URL = '/accounts/landing/'  # or '/accounts/login/'
# SESSION_COOKIE_SECURE = False
# CSRF_COOKIE_SECURE = False

# SESSION_COOKIE_AGE = 3600  # 1 hour
# SESSION_EXPIRE_AT_BROWSER_CLOSE = True # Optional: Expire session on browser close
# SOCIAL_AUTH_LOGIN_ERROR_URL = '/login-error/'
# SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# SOCIAL_AUTH_RAISE_EXCEPTIONS = False

# SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = config('495716495349-3es52lkdon6bjb2ma4huoekt5jqjqimi.apps.googleusercontent.com')
# # '575256574699-8h5kelkch088673opdm32goo15ftve1k.apps.googleusercontent.com'
# SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = config('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')
# SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_DOMAINS = [
#     'mitsgwl.ac.in', # Student domain
#     # 'mitsgwalior.in', # Faculty domain
#     'gmail.com'  # Warden/faculty domain
# ]

# # 🔘 Force Google to show the "Choose an account" screen at every login
# SOCIAL_AUTH_GOOGLE_OAUTH2_AUTH_EXTRA_ARGUMENTS = {
#     'prompt': 'select_account'
# }
# # SOCIAL_AUTH_GOOGLE_OAUTH2_IGNORE_DEFAULT_SCOPE = True


# SOCIAL_AUTH_PIPELINE = [
#     'social_core.pipeline.social_auth.social_details',          # Extract basic profile info
#     'social_core.pipeline.social_auth.social_uid',             # Get unique user ID from provider
#     'accounts.pipeline.auth_allowed',                          # ✅ Custom domain/CSV check
#     'social_core.pipeline.social_auth.social_user',             # Try to find existing user
#     'social_core.pipeline.user.get_username',                   # Generate username if needed
#     'social_core.pipeline.user.create_user',                    # Create new user if not found
#     'accounts.pipeline.assign_role',                            # ✅ Assign StudentProfile or WardenProfile
#     'accounts.pipeline.extract_name_and_enrollment',            # ✅ Parse Google name for students
#     'accounts.pipeline.redirect_after_login',                   # ✅ Route to correct dashboard
#     'social_core.pipeline.social_auth.associate_user',          # Link social account to user
#     'social_core.pipeline.social_auth.load_extra_data',         # Load extra data from provider
#     'social_core.pipeline.user.user_details',                   # Update user model fields
# ]
# SESSION_ENGINE = 'django.contrib.sessions.backends.db'
# SESSION_COOKIE_NAME = 'sessionid'
# SESSION_COOKIE_SECURE = False
# SESSION_COOKIE_SAMESITE = 'Lax'
# CSRF_COOKIE_SECURE = False


# STATIC_ROOT = BASE_DIR / 'staticfiles'

# # 🌐 Media files (Student uploaded complaint images)
# MEDIA_URL = '/media/'
# MEDIA_ROOT = BASE_DIR / 'media'

# # 📧 Email Configuration (Student Welcome & Notifications)
# # Defaulting to Console for easy terminal testing!
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# # --- Gmail SMTP Template (Uncomment for Real Emails) ---
# # EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# # EMAIL_HOST = 'smtp.gmail.com'
# # EMAIL_PORT = 587
# # EMAIL_USE_TLS = True
# # EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
# # EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
# # DEFAULT_FROM_EMAIL = f"Hostel Portal <{config('EMAIL_HOST_USER', default='')}>"




"""
Django settings for hostel_portal project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--k^i@#ri*g!a*yb(iaea!)kgw6_ab^0uq!cule83zj5wjf5!kx'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = []
DEBUG = config('DEBUG', default=False, cast=bool)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost').split(',')

# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',  # DISABLED — using custom master_admin instead
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'social_django',
    'warden',
    'complaints',
    'faculty',
    'master_admin',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
    'accounts.middleware.CustomSocialAuthExceptionMiddleware',
    'accounts.middleware.SafeNavigationMiddleware',
]

ROOT_URLCONF = 'hostel_portal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',         # ✅ Add this
                'social_django.context_processors.login_redirect',   # ✅ And this
            ],
        },
    },
]


WSGI_APPLICATION = 'hostel_portal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


# Create a New Database, in postgres
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'hostel_portal',           # pgAdmin DB name
        'USER': 'postgres',            # pgAdmin username
        'PASSWORD': '1234',            # pgAdmin password
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [ BASE_DIR / 'static' ]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



#============ADDED===============

AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

LOGIN_URL = 'google_login_redirect'         # This should match your redirect view name
# LOGIN_REDIRECT_URL = 'profile_edit'      # After login, go to profile edit
LOGIN_REDIRECT_URL =   '/accounts/login-redirect/'  # ✅ Safe fallback, pipeline will override
# LOGOUT_REDIRECT_URL = 'google_login_redirect'
LOGOUT_REDIRECT_URL = '/accounts/landing/'  # or '/accounts/login/'
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False

SESSION_COOKIE_AGE = 3600  # 1 hour
SESSION_EXPIRE_AT_BROWSER_CLOSE = True # Optional: Expire session on browser close
SOCIAL_AUTH_LOGIN_ERROR_URL = '/?error=unauthorized'
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

SOCIAL_AUTH_RAISE_EXCEPTIONS = False

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = config('GOOGLE_CLIENT_ID', default='150914122946-9bbpo1brfbtjqpick41mc5eot1q5d995.apps.googleusercontent.com')
# '575256574699-8h5kelkch088673opdm32goo15ftve1k.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = config('GOOGLE_SECRET_KEY', default='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')
SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_DOMAINS = [
    'mitsgwl.ac.in', # Student domain
    'mitsgwalior.in', # Faculty domain
    'gmail.com'  # Warden/faculty domain
]

# 👑 Master Admin Emails
ADMIN_EMAILS = [e.strip().lower() for e in config('ADMIN_EMAILS', default='').split(',') if e.strip()]
# 
# 🧪 Test Users (Bypasses Database Pre-approval)
TEST_WARDEN_EMAIL = config('TEST_WARDEN_EMAIL', default='').lower().strip()
TEST_WARDEN_NAME = config('TEST_WARDEN_NAME', default='Testing Warden')
TEST_WARDEN_HOSTEL = config('TEST_WARDEN_HOSTEL', default='Hostel 1')

TEST_FACULTY_EMAIL = config('TEST_FACULTY_EMAIL', default='').lower().strip()
TEST_FACULTY_NAME = config('TEST_FACULTY_NAME', default='Testing Faculty')


# 🔘 Force Google to show the "Choose an account" screen at every login
SOCIAL_AUTH_GOOGLE_OAUTH2_AUTH_EXTRA_ARGUMENTS = {
    'prompt': 'select_account'
}
# SOCIAL_AUTH_GOOGLE_OAUTH2_IGNORE_DEFAULT_SCOPE = True


SOCIAL_AUTH_PIPELINE = [
    'social_core.pipeline.social_auth.social_details',          # Extract basic profile info
    'social_core.pipeline.social_auth.social_uid',             # Get unique user ID from provider
    'accounts.pipeline.auth_allowed',                          # ✅ Custom domain/CSV check
    'social_core.pipeline.social_auth.social_user',             # Try to find existing user
    'social_core.pipeline.user.get_username',                   # Generate username if needed
    'social_core.pipeline.user.create_user',                    # Create new user if not found
    'accounts.pipeline.assign_role',                            # ✅ Assign StudentProfile or WardenProfile
    'accounts.pipeline.extract_name_and_enrollment',            # ✅ Parse Google name for students
    'accounts.pipeline.redirect_after_login',                   # ✅ Route to correct dashboard
    'social_core.pipeline.social_auth.associate_user',          # Link social account to user
    'social_core.pipeline.social_auth.load_extra_data',         # Load extra data from provider
    'social_core.pipeline.user.user_details',                   # Update user model fields
]
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_NAME = 'sessionid'
SESSION_COOKIE_SECURE = False
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = False


STATIC_ROOT = BASE_DIR / 'staticfiles'

# 🌐 Media files (Student uploaded complaint images)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# 📧 Email Configuration (Student Welcome & Notifications)
# Defaulting to Console for easy terminal testing!
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# --- Gmail SMTP Template (Uncomment for Real Emails) ---
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
# EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
# DEFAULT_FROM_EMAIL = f"Hostel Portal <{config('EMAIL_HOST_USER', default='')}>"