"""
Django settings for hostel_portal project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--k^i@#ri*g!a*yb(iaea!)kgw6_ab^0uq!cule83zj5wjf5!kx'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = []
DEBUG = config('DEBUG', default=False, cast=bool)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost').split(',')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'social_django',


]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
]

ROOT_URLCONF = 'hostel_portal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',         # ✅ Add this
                'social_django.context_processors.login_redirect',   # ✅ And this
            ],
        },
    },
]


WSGI_APPLICATION = 'hostel_portal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


# Create a New Database, in postgres
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'hostel_portal',           # pgAdmin DB name
        'USER': 'postgres',            # pgAdmin username
        'PASSWORD': '1234',            # pgAdmin password
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [ BASE_DIR / 'static' ]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



#============ADDED===============

AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

LOGIN_URL = 'google_login_redirect'         # 👈 This should match your redirect view name
# LOGIN_REDIRECT_URL = 'profile_edit'      # 👈 After login, go to profile edit
LOGIN_REDIRECT_URL = '/accounts/dashboard/'  # ✅ Safe fallback, pipeline will override
# LOGOUT_REDIRECT_URL = 'google_login_redirect'
LOGOUT_REDIRECT_URL = '/accounts/login/'  # or '/accounts/login/'
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False

SESSION_COOKIE_AGE = 3600  # 1 hour
SESSION_EXPIRE_AT_BROWSER_CLOSE = True # Optional: Expire session on browser close
SOCIAL_AUTH_LOGIN_ERROR_URL = '/login-error/'
SESSION_ENGINE = 'django.contrib.sessions.backends.db'


SOCIAL_AUTH_RAISE_EXCEPTIONS = False


SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '575256574699-8h5kelkch088673opdm32goo15ftve1k.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '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'
SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_DOMAINS = [
    'mitsgwl.ac.in', # Student domain
    'mitsgwalior.in', # Faculty domain
]
# SOCIAL_AUTH_GOOGLE_OAUTH2_IGNORE_DEFAULT_SCOPE = True


SOCIAL_AUTH_PIPELINE = [
    'social_core.pipeline.social_auth.social_details',          # Extract basic profile info
    'social_core.pipeline.social_auth.social_uid',             # Get unique user ID from provider
    'accounts.pipeline.auth_allowed',                  # ✅ Use your custom check here            
    'social_core.pipeline.social_auth.auth_allowed',            # Check if login is allowed
    'social_core.pipeline.social_auth.social_user',             # Try to find existing user
    'social_core.pipeline.user.get_username',                   # Generate username if needed
    'social_core.pipeline.user.create_user',                    # Create new user if not found
    'accounts.pipeline.assign_role',  # ✅ login happens here
    # 'accounts.pipeline.clean_session',                    # ✅ flush before profile logic
    'accounts.pipeline.extract_name_and_enrollment',      # ✅ Your custom step
    'accounts.pipeline.redirect_after_login',             # ✅ Your custom step
    
    'social_core.pipeline.social_auth.associate_user',          # Link social account to user
    'social_core.pipeline.social_auth.load_extra_data',         # Load extra data from provider
    'social_core.pipeline.user.user_details',                   # Update user model fields
    'accounts.middleware.SocialAuthExceptionMiddleware',  # ✅ Your custom middleware
]
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_NAME = 'sessionid'
SESSION_COOKIE_SECURE = False
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = False
