# Generated by Django 5.2.7 on 2025-10-14 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='alt_parent_mobile',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_mobile', message='Enter a valid 10-digit mobile number.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='mobile',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_mobile', message='Enter a valid 10-digit mobile number.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='parent_mobile',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_mobile', message='Enter a valid 10-digit mobile number.', regex='^\\d{10}$')]),
        ),
    ]
