# Generated by Django 5.2.7 on 2025-10-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_allowedstudent_studentprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedstudent',
            name='branch',
            field=models.CharField(default='CSE', max_length=50),
        ),
        migrations.AddField(
            model_name='allowedstudent',
            name='enrollment_number',
            field=models.CharField(default='0000TEST', max_length=20),
        ),
        migrations.AddField(
            model_name='allowedstudent',
            name='full_name',
            field=models.CharField(default='TEST USER', max_length=100),
        ),
        migrations.AlterField(
            model_name='allowedstudent',
            name='email',
            field=models.EmailField(default='test@mitsgwl.ac.in', max_length=254, unique=True),
        ),
    ]
