# Generated by Django 5.2.7 on 2025-11-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_allowedstudent_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
    ]
