# Generated by Django 5.2.7 on 2026-04-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_studentprofile_branch_studentprofile_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedstudent',
            name='semester',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
