# Generated by Django 5.2.7 on 2026-04-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_allowedstudent_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedstudent',
            name='floor_number',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='allowedstudent',
            name='room_number',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='floor_number',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='room_number',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
