# Generated by Django 5.2.7 on 2026-04-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_allowedstudent_floor_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedstudent',
            name='assigned_hostel',
            field=models.CharField(default='Hostel 1', max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='assigned_hostel',
            field=models.CharField(blank=True, default='Hostel 1', max_length=50),
        ),
    ]
