# Generated by Django 5.2.7 on 2026-04-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_allowedfaculty_allowedwarden_adminprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='enrollment_number',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
