# Generated by Django 5.2.7 on 2026-04-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_studentprofile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedfaculty',
            name='mobile',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='allowedwarden',
            name='mobile',
            field=models.CharField(default='', max_length=10),
        ),
    ]
