# Generated by Django 5.2.7 on 2026-04-13 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_allowedfaculty_mobile_allowedwarden_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedstudent',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
