# Generated by Django 5.2.7 on 2026-04-14 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_allowedstudent_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='alt_parent_mobile',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='parent_mobile',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='state',
        ),
    ]
