# Generated by Django 5.2.7 on 2026-04-14 11:38

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_studentprofile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowedwarden',
            name='id',
        ),
        migrations.AddField(
            model_name='allowedwarden',
            name='url_key',
            field=models.CharField(default=accounts.models._generate_url_key, editable=False, max_length=16),
        ),        migrations.AlterField(
            model_name='allowedwarden',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
