# Generated by Django 5.2.7 on 2026-04-14 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_allowedwarden_id_allowedwarden_url_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowedfaculty',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='allowedwarden',
            name='mobile',
        ),
    ]
