# Generated by Django 5.2.7 on 2026-04-14 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_allowedfaculty_mobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowedfaculty',
            name='department',
        ),
    ]
