# Generated by Django 5.2.7 on 2026-04-14 17:29

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_allowedfaculty_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedwarden',
            name='url_key',
            field=models.CharField(default=accounts.models._generate_url_key, editable=False, max_length=16, unique=True),
        ),
    ]
